# Generated by Django 4.2.30 on 2026-06-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nia_app', '0005_seed_master_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advicenumbermaster',
            options={'ordering': ['-created_at'], 'verbose_name': 'Advice Number Master', 'verbose_name_plural': 'Advice Number Masters'},
        ),
        migrations.AlterModelOptions(
            name='cismaster',
            options={'ordering': ['province', 'cis_name'], 'verbose_name': 'CIS Master', 'verbose_name_plural': 'CIS Masters'},
        ),
        migrations.AlterModelOptions(
            name='descriptionmaster',
            options={'ordering': ['value'], 'verbose_name': 'Description Master', 'verbose_name_plural': 'Description Masters'},
        ),
        migrations.AlterModelOptions(
            name='gaasaromaster',
            options={'ordering': ['value'], 'verbose_name': 'GAA/SARO Master', 'verbose_name_plural': 'GAA/SARO Masters'},
        ),
        migrations.AlterModelOptions(
            name='objectcodemaster',
            options={'ordering': ['value'], 'verbose_name': 'Object Code Master', 'verbose_name_plural': 'Object Code Masters'},
        ),
        migrations.AlterModelOptions(
            name='suballotmentadvice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sub-Allotment Advice', 'verbose_name_plural': 'Sub-Allotment Advices'},
        ),
        migrations.AlterField(
            model_name='allotmentstatement',
            name='ada_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='allotmentstatement',
            name='allotment_received',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='allotmentstatement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='allotmentstatement',
            name='project_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='allotmentstatement',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cisallotment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='provinceallotment',
            name='province_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='advice_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='calendar_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='fund_code',
            field=models.CharField(blank=True, default='501', max_length=20),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='object_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='region',
            field=models.CharField(choices=[('1', 'Region 1'), ('2', 'Region 2'), ('3', 'Region 3'), ('4A', 'Region 4A'), ('4B', 'Region 4B'), ('5', 'Region 5'), ('6', 'Region 6'), ('7', 'Region 7'), ('8', 'Region 8'), ('9', 'Region 9'), ('10', 'Region 10'), ('11', 'Region 11'), ('12', 'Region 12'), ('13', 'Region 13 - Caraga'), ('CAR', 'CAR'), ('NCR', 'NCR'), ('BARMM', 'BARMM')], default='13', max_length=10),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='to_office',
            field=models.CharField(blank=True, default='REGIONAL IRRIGATION MANAGER', max_length=200),
        ),
    ]
