# Generated by Django 4.2.30 on 2026-06-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nia_app', '0006_alter_advicenumbermaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentstatement',
            name='ada_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='allotmentstatement',
            name='object_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
