# Generated by Django 4.2.30 on 2026-06-10 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nia_app', '0008_allotmentstatement_fund_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allotmentstatement',
            name='cis_name',
        ),
        migrations.RemoveField(
            model_name='allotmentstatement',
            name='fund_type',
        ),
        migrations.RemoveField(
            model_name='allotmentstatement',
            name='province',
        ),
        migrations.RemoveField(
            model_name='allotmentstatement',
            name='source_advice',
        ),
        migrations.AlterField(
            model_name='allotmentstatement',
            name='object_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allotment_statements', to='nia_app.objectcodemaster'),
        ),
        migrations.AlterField(
            model_name='allotmentstatement',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allotment_statements', to='nia_app.descriptionmaster'),
        ),
        migrations.AlterField(
            model_name='cisallotment',
            name='cis_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cis_allotments', to='nia_app.cismaster'),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='advice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_allotments', to='nia_app.advicenumbermaster'),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_allotments', to='nia_app.descriptionmaster'),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='gaa_saro_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_allotments', to='nia_app.gaasaromaster'),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='object_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_allotments', to='nia_app.objectcodemaster'),
        ),
    ]
