
# Generated by Django 4.2.30 on 2026-06-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nia_app', '0009_remove_allotmentstatement_cis_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotmentstatement',
            name='object_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='allotmentstatement',
            name='project_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cisallotment',
            name='cis_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='advice_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='gaa_saro_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='suballotmentadvice',
            name='object_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
