# Generated by Django 4.2.30 on 2026-06-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nia_app', '0010_alter_allotmentstatement_object_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(choices=[('ADN', 'Agusan del Norte'), ('ADS', 'Agusan del Sur'), ('SDN', 'Surigao del Norte'), ('SDS', 'Surigao del Sur'), ('RIO', 'Regional Irrigation Office')], max_length=10)),
                ('province', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs_of_work', to='nia_app.suballotmentadvice')),
            ],
            options={
                'verbose_name': 'Program of Work',
                'verbose_name_plural': 'Programs of Work',
                'ordering': ['-created_at'],
                'unique_together': {('advice', 'office', 'province')},
            },
        ),
        migrations.CreateModel(
            name='ProgramOfWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('pow_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('imo_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mo_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nia_app.programofwork')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('program', 'item')},
            },
        ),
    ]
